on: [push]
name: Azure ARM Microservice 1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: ${{ secrets.AZURE_RG }}
      ResourceGroupLocation: "westus"
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create resource group if it doesn't exist
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"

      # Deploy ARM template -vnet
    - name: Run ARM deploy - vnet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./template-vnet.json
    
      # Deploy ARM template - vm scalesets
    - name: Run ARM deploy - vm scaleset
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.ResourceGroupName }}
        deploymentName: "MS1 vmss"
        template: ./template-vmss.json
        parameters: ./parameters-vmss-ms1.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}