on: [push]
name: Azure-ARM-VNet
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template -vnet
    - name: Run ARM deploy - vnet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        deploymentName: ${{ github.workflow }}-${{ github.run_id }}
        template: ./vnet/template-vnet.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}