on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - DEV
        - PROD
        required: true
name: deployVNet
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      # Deploy ARM template -vnet
    - name: Run ARM deploy - vnet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_DEV }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        deploymentName: ${{ github.workflow }}-${{ github.run_id }}
        template: ./vnet/template-vnet.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}