on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template -vnet
    - name: Run ARM deploy - vnet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./template-vnet.json
    
      # Deploy ARM template - availability sets
    - name: Run ARM deploy - availability sets
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./template-availability.json
        parameters: ./parameters-availability.json

      # Deploy ARM template - deploy instances
    - name: Run ARM deploy - deploy instances
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./template-instance.json
        parameters: ./parameters-instance.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}