on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - prod
        required: true
name: Azure-ARM-MS1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: ${{ secrets.AZURE_RG }}
      ResourceGroupLocation: "westus"
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}_${{ env.ENVIRONMENT }}

      # Create resource group if it doesn't exist
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"
    
      # Deploy ARM template - vm scalesets
    - name: Run ARM deploy - vm scaleset
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}_${{ env.ENVIRONMENT }}
        resourceGroupName: ${{ env.ResourceGroupName }}
        deploymentName: ${{ github.workflow }}-${{ github.run_id}}
        template: ./vmss/template-vmss.json
        parameters: ./vmss/parameters-vmss-ms1.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}