on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - DEV
        - PROD
        required: true
name: Azure-ARM-VNet
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: ${{ secrets.AZURE_RG }}
      ResourceGroupLocation: "westus"
      ENVIRONMENT: ${{ inputs.environment }}
      AZURE_CREDENTIALS: secrets.AZURE_CREDENTIALS_${{ inputs.environment }}
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ ${{ env.AZURE_CREDENTIALS }} }}

      # Create resource group if it doesn't exist
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"

      # Deploy ARM template -vnet
    - name: Run ARM deploy - vnet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}_${{ env.ENVIRONMENT }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        deploymentName: ${{ github.workflow }}-${{ github.run_id }}
        template: ./vnet/template-vnet.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}